# Generated by Django 4.2.16 on 2024-09-26 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "high_level",
            "0002_machine_produit_ressource_alter_ville_code_postal_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="etape",
            name="etape_suivante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="high_level.etape",
            ),
        ),
        migrations.RemoveField(
            model_name="usine",
            name="machines",
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.IntegerField(max_length=100)),
                ("ressource", models.ManyToManyField(to="high_level.ressource")),
            ],
        ),
        migrations.AddField(
            model_name="usine",
            name="machines",
            field=models.ManyToManyField(to="high_level.machine"),
        ),
    ]
