# Generated by Django 4.2.16 on 2024-09-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "high_level",
            "0003_etape_etape_suivante_remove_usine_machines_stock_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="usine",
            field=models.ForeignKey(
                default=0.0,
                on_delete=django.db.models.deletion.CASCADE,
                to="high_level.usine",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="stock",
            name="ressource",
        ),
        migrations.AddField(
            model_name="stock",
            name="ressource",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="high_level.ressource",
            ),
            preserve_default=False,
        ),
    ]
