# Generated by Django 5.1.1 on 2024-10-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0006_remove_stock_ressource_remove_stock_usine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usine",
            name="stock",
            field=models.ManyToManyField(to="high_level.stock"),
        ),
    ]
