# Generated by Django 5.1.1 on 2024-10-01 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0007_usine_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usine",
            name="stock",
        ),
        migrations.AddField(
            model_name="usine",
            name="stock",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.stock",
            ),
        ),
    ]
