# Generated by Django 5.1.1 on 2024-11-01 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0008_remove_usine_stock_usine_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="quantiteRessource",
        ),
        migrations.AddField(
            model_name="stock",
            name="ressource",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="high_level.ressource",
            ),
        ),
        migrations.RemoveField(
            model_name="usine",
            name="stock",
        ),
        migrations.AddField(
            model_name="usine",
            name="stock",
            field=models.ManyToManyField(to="high_level.stock"),
        ),
    ]
